import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import FreshNavbar from "@/components/fresh_basket-home/FreshNavbar/FreshNavbar";
import FreshFooter from "@/components/fresh_basket-home/FreshFooter/FreshFooter";
import TanstackProvider from "@/components/tanstack_provider/TanstackProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <Provider>
            <FreshNavbar />
            {children}
            <FreshFooter />
          </Provider>
        </TanstackProvider>
      </body>
    </html>
  );
}
