import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import FreshNavbar from "@/components/fresh_basket-home/FreshNavbar/FreshNavbar";
import FreshFooter from "@/components/fresh_basket-home/FreshFooter/FreshFooter";
import TanstackProvider from "@/components/tanstack_provider/TanstackProvider";
import { Toaster } from "@/components/ui/toaster";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${roboto.className} antialiased`}>
        <TanstackProvider>
          <Provider>
            <FreshNavbar />
            {children}
            <FreshFooter />
            <Toaster />
          </Provider>
        </TanstackProvider>
      </body>
    </html>
  );
}
